use std::collections::hash_map::DefaultHasher;
use std::hash::{Hash as StdHash, Hasher};

/// Base directory for all project files on this agent.
pub(crate) fn projects_dir() -> std::path::PathBuf {
    std::path::PathBuf::from("projects")
}

/// Ensure the project-specific directory exists and has a placeholder .env if missing.
pub(crate) fn ensure_project_dir_and_env(project_id: &str) {
    let project_dir = projects_dir().join(project_id);
    if let Err(e) = std::fs::create_dir_all(&project_dir) {
        tracing::error!(project = project_id, error = %e, "failed to create project directory");
        return;
    }

    let env_path = project_dir.join(".env");
    if !env_path.exists() {
        let placeholder = "# Place your runtime environment variables here\n# These variables are injected directly into your container at startup.\n";
        if let Err(e) = std::fs::write(&env_path, placeholder) {
            tracing::error!(project = project_id, error = %e, "failed to create placeholder .env");
        } else {
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                let _ = std::fs::set_permissions(&env_path, std::fs::Permissions::from_mode(0o600));
            }
            tracing::info!(project = project_id, path = %env_path.display(), "created placeholder .env");
        }
    }
}

/// Read env vars from `projects/<project_id>/.env` if it exists.
pub fn read_project_env(project_id: &str) -> Vec<String> {
    // First, ensure the directory and placeholder exist
    ensure_project_dir_and_env(project_id);

    let env_path = projects_dir().join(project_id).join(".env");
    tracing::info!(project = project_id, path = %env_path.display(), exists = env_path.exists(), "checking for .env file");

    if !env_path.exists() {
        return Vec::new();
    }

    match dotenvy::from_path_iter(&env_path) {
        Ok(iter) => {
            let vars: Vec<String> = iter
                .filter_map(|item| item.ok())
                .map(|(k, v)| format!("{}={}", k, v))
                .collect();
            tracing::info!(project = project_id, count = vars.len(), "env var(s) loaded from .env");
            vars
        }
        Err(e) => {
            tracing::warn!(project = project_id, path = %env_path.display(), error = %e, "failed to parse .env");
            Vec::new()
        }
    }
}

/// Hash a file's raw content. Returns 0 if the file doesn't exist.
fn file_hash(path: &std::path::Path) -> u64 {
    match std::fs::read(path) {
        Ok(bytes) => {
            let mut hasher = DefaultHasher::new();
            bytes.hash(&mut hasher);
            hasher.finish()
        }
        Err(_) => 0,
    }
}

/// Hash the content portion of a .env.l8bin snapshot (strips the 5-line header).
/// Returns 0 if the file doesn't exist.
fn snapshot_content_hash(path: &std::path::Path) -> u64 {
    let content = match std::fs::read_to_string(path) {
        Ok(c) => c,
        Err(_) => return 0,
    };
    // Skip the header: 4 comment lines + 1 blank line
    let payload: String = content.lines().skip(5).collect::<Vec<_>>().join("\n");
    let mut hasher = DefaultHasher::new();
    payload.hash(&mut hasher);
    hasher.finish()
}

/// Check if the project .env has changed since the last container creation.
/// Compares .env hash against .env.l8bin snapshot hash (header stripped).
pub fn env_has_changed(project_id: &str) -> bool {
    let env_path = projects_dir().join(project_id).join(".env");
    let snapshot_path = projects_dir().join(project_id).join(".env.l8bin");

    let env_hash = file_hash(&env_path);
    // .env.l8bin has a 5-line header (4 comments + blank line) — strip it before hashing
    let snapshot_hash = snapshot_content_hash(&snapshot_path);

    let changed = env_hash != snapshot_hash;
    tracing::info!(project = project_id, env_hash = env_hash, snapshot_hash = snapshot_hash, changed = changed, "env change check");
    changed
}

/// Write .env.l8bin snapshot — a copy of the current .env with a header.
/// Called after successfully creating a container with injected env vars.
pub fn write_env_snapshot(project_id: &str) {
    let env_path = projects_dir().join(project_id).join(".env");
    let snapshot_path = projects_dir().join(project_id).join(".env.l8bin");

    let content = match std::fs::read_to_string(&env_path) {
        Ok(c) => c,
        Err(_) => return,
    };

    let header = "# Auto-generated by LiteBin — do not edit manually.\n\
        # This records the env vars last injected into your container.\n\
        # Compare with .env to see pending changes.\n\
        # Docs: https://github.com/mtsandeep/l8bin/blob/main/docs/env-secrets.md\n";

    if let Err(e) = std::fs::write(&snapshot_path, format!("{}\n{}", header, content)) {
        tracing::warn!(project = project_id, error = %e, "failed to write .env.l8bin snapshot");
    } else {
        tracing::info!(project = project_id, "wrote .env.l8bin snapshot");
    }
}
