use axum::http::StatusCode;
use serde::Deserialize;
use serde::Serialize;
use serde_json::json;
use std::hash::Hasher;

use litebin_common::types::Node;
use crate::nodes;
use crate::AppState;

#[derive(Serialize, Default)]
pub struct MessageResponse {
    pub message: String,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub warnings: Vec<String>,
}

/// Build the base URL for an agent node.
pub fn agent_base_url(config: &crate::config::Config, node: &Node) -> String {
    if config.ca_cert_path.is_empty() {
        format!("http://{}:{}", node.host, node.agent_port)
    } else {
        format!("https://{}:{}", node.host, node.agent_port)
    }
}

/// Fetch a Node record from the DB by node_id.
pub async fn get_node_from_db(
    db: &sqlx::SqlitePool,
    node_id: &str,
) -> Result<Node, (StatusCode, String)> {
    sqlx::query_as::<_, Node>("SELECT * FROM nodes WHERE id = ?")
        .bind(node_id)
        .fetch_optional(db)
        .await
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, format!("db error: {e}")))?
        .ok_or_else(|| (StatusCode::NOT_FOUND, format!("node '{}' not found", node_id)))
}

/// Ensure the project-specific directory exists and has a placeholder .env if missing.
pub fn ensure_project_dir_and_env(project_id: &str) {
    let project_dir = std::path::PathBuf::from("projects").join(project_id);
    if let Err(e) = std::fs::create_dir_all(&project_dir) {
        tracing::error!(project = project_id, error = %e, "failed to create project directory");
        return;
    }

    let env_path = project_dir.join(".env");
    if !env_path.exists() {
        let placeholder = "# Place your runtime environment variables here\n# These variables are injected directly into your container at startup.\n";
        if let Err(e) = std::fs::write(&env_path, placeholder) {
            tracing::error!(project = project_id, error = %e, "failed to create placeholder .env");
        } else {
            tracing::info!(project = project_id, path = %env_path.display(), "created placeholder .env");
        }
    }
}

/// Read env vars from the local project .env file.
pub fn read_local_project_env(project_id: &str) -> Vec<String> {
    // Ensure the directory and placeholder exist
    ensure_project_dir_and_env(project_id);

    let env_path = std::path::PathBuf::from("projects").join(project_id).join(".env");
    if !env_path.exists() {
        return Vec::new();
    }
    match dotenvy::from_path_iter(&env_path) {
        Ok(iter) => iter
            .filter_map(|item| item.ok())
            .map(|(k, v)| format!("{}={}", k, v))
            .collect(),
        Err(e) => {
            tracing::warn!(project = project_id, error = %e, "failed to parse .env");
            Vec::new()
        }
    }
}

/// Check if the project .env has changed since the last container creation.
/// Compares current .env hash against the .env.l8bin snapshot.
pub fn local_env_has_changed(project_id: &str) -> bool {
    let env_path = std::path::PathBuf::from("projects").join(project_id).join(".env");
    let snapshot_path = std::path::PathBuf::from("projects").join(project_id).join(".env.l8bin");

    let env_hash = file_hash(&env_path);
    // .env.l8bin has a 5-line header (4 comments + blank line) — strip it before hashing
    let snapshot_hash = snapshot_content_hash(&snapshot_path);

    let changed = env_hash != snapshot_hash;
    if changed {
        tracing::info!(project = project_id, env_hash = env_hash, snapshot_hash = snapshot_hash, "env has changed since last container creation");
    }
    changed
}

fn file_hash(path: &std::path::Path) -> u64 {
    match std::fs::read(path) {
        Ok(bytes) => {
            let mut hasher = std::collections::hash_map::DefaultHasher::new();
            std::hash::Hash::hash(&bytes, &mut hasher);
            hasher.finish()
        }
        Err(_) => 0,
    }
}

fn snapshot_content_hash(path: &std::path::Path) -> u64 {
    let content = match std::fs::read_to_string(path) {
        Ok(c) => c,
        Err(_) => return 0,
    };
    // Skip the header: 4 comment lines + 1 blank line
    let payload: String = content.lines().skip(5).collect::<Vec<_>>().join("\n");
    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    std::hash::Hash::hash(&payload, &mut hasher);
    hasher.finish()
}

/// Write .env.l8bin snapshot — a copy of the current .env with a header.
/// Called after successfully creating a container with injected env vars.
pub fn write_local_env_snapshot(project_id: &str) {
    let env_path = std::path::PathBuf::from("projects").join(project_id).join(".env");
    let snapshot_path = std::path::PathBuf::from("projects").join(project_id).join(".env.l8bin");

    let content = match std::fs::read_to_string(&env_path) {
        Ok(c) => c,
        Err(_) => return,
    };

    let header = "# Auto-generated by LiteBin — do not edit manually.\n\
        # This records the env vars last injected into your container.\n\
        # Compare with .env to see pending changes.\n\
        # Docs: https://github.com/mtsandeep/l8bin/blob/main/docs/env-secrets.md\n";

    if let Err(e) = std::fs::write(&snapshot_path, format!("{}\n{}", header, content)) {
        tracing::warn!(project = project_id, error = %e, "failed to write .env.l8bin snapshot");
    } else {
        tracing::info!(project = project_id, "wrote .env.l8bin snapshot");
    }
}

/// Remove an image from the node if no container is using it.
/// All errors are logged and swallowed — cleanup must never block the caller.
pub async fn cleanup_unused_image(state: &AppState, node_id: Option<&str>, image: &str) {
    let node_id = node_id.unwrap_or("local");
    if node_id == "local" {
        match state.docker.remove_unused_image(image).await {
            Ok(true) => tracing::info!(image = %image, "cleaned up unused local image"),
            Ok(false) => {}
            Err(e) => tracing::warn!(image = %image, error = %e, "failed to clean up local image"),
        }
    } else {
        let client = match nodes::client::get_node_client(&state.node_clients, node_id) {
            Ok(c) => c,
            Err(e) => {
                tracing::warn!(node_id = %node_id, error = %e, "cleanup: node client unavailable");
                return;
            }
        };
        let node = match get_node_from_db(&state.db, node_id).await {
            Ok(n) => n,
            Err(e) => {
                tracing::warn!(node_id = %node_id, error = ?e, "cleanup: node not found");
                return;
            }
        };
        let base_url = agent_base_url(&state.config, &node);
        match client
            .post(format!("{}/images/remove-unused", base_url))
            .json(&json!({ "image": image }))
            .send()
            .await
        {
            Ok(resp) if resp.status().is_success() => {
                tracing::info!(image = %image, node_id = %node_id, "cleaned up unused remote image");
            }
            Ok(resp) => {
                tracing::warn!(image = %image, node_id = %node_id, status = %resp.status(), "cleanup: agent returned non-success");
            }
            Err(e) => {
                tracing::warn!(image = %image, node_id = %node_id, error = %e, "cleanup: agent unreachable");
            }
        }
    }
}

/// Resolve an image reference (tag, digest, or ID) to its sha256 digest on the given node.
/// Returns None on any failure (image not found, node unreachable) — best-effort, never blocks.
pub async fn get_image_digest(
    state: &AppState,
    node_id: Option<&str>,
    image: &str,
) -> Option<String> {
    let node_id = node_id.unwrap_or("local");
    if node_id == "local" {
        match state.docker.inspect_image_id(image).await {
            Ok(digest) => Some(digest),
            Err(e) => {
                tracing::debug!(image = %image, error = %e, "could not resolve local image digest");
                None
            }
        }
    } else {
        let client = match nodes::client::get_node_client(&state.node_clients, node_id) {
            Ok(c) => c,
            Err(e) => {
                tracing::debug!(node_id = %node_id, error = %e, "inspect: node client unavailable");
                return None;
            }
        };
        let node = match get_node_from_db(&state.db, node_id).await {
            Ok(n) => n,
            Err(e) => {
                tracing::debug!(node_id = %node_id, error = ?e, "inspect: node not found");
                return None;
            }
        };
        let base_url = agent_base_url(&state.config, &node);
        #[derive(Deserialize)]
        struct InspectResponse {
            image_id: String,
        }
        match client
            .get(format!("{}/images/inspect?image={}", base_url, image))
            .send()
            .await
        {
            Ok(resp) if resp.status().is_success() => {
                match resp.json::<InspectResponse>().await {
                    Ok(body) => Some(body.image_id),
                    Err(e) => {
                        tracing::debug!(image = %image, error = %e, "inspect: failed to parse agent response");
                        None
                    }
                }
            }
            Ok(resp) => {
                tracing::debug!(image = %image, status = %resp.status(), "inspect: agent returned non-success");
                None
            }
            Err(e) => {
                tracing::debug!(image = %image, error = %e, "inspect: agent unreachable");
                None
            }
        }
    }
}

/// Capture image digests for per-service images from the DB.
/// Optionally filters to only `target_services`. Skips `sha256:` prefixed images.
pub async fn capture_service_digests(
    state: &AppState,
    project_id: &str,
    node_id: Option<&str>,
    target_services: Option<&std::collections::HashSet<String>>,
) -> std::collections::HashMap<String, String> {
    let services: Vec<(String, String)> = sqlx::query_as(
        "SELECT service_name, image FROM project_services WHERE project_id = ?",
    )
    .bind(project_id)
    .fetch_all(&state.db)
    .await
    .unwrap_or_default();

    let mut digests = std::collections::HashMap::new();
    for (svc_name, image) in &services {
        if let Some(ref filter) = target_services {
            if !filter.contains(svc_name) {
                continue;
            }
        }
        if !image.starts_with("sha256:") {
            if let Some(d) = get_image_digest(state, node_id, image).await {
                digests.insert(svc_name.clone(), d);
            }
        }
    }
    digests
}

pub async fn sync_caddy(state: &AppState) {
    let routes = match crate::routing_helpers::resolve_all_routes(
        &state.db, &state.config.domain, &format!("litebin-orchestrator:{}", state.config.port),
    ).await {
        Ok(r) => r,
        Err(e) => {
            tracing::error!(error = %e, "failed to resolve routes");
            return;
        }
    };

    let upstream = format!("litebin-orchestrator:{}", state.config.port);
    if let Err(e) = state
        .router
        .read()
        .await
        .sync_routes(&routes, &state.config.domain, &upstream, &state.config.dashboard_subdomain, &state.config.poke_subdomain, true)
        .await
    {
        tracing::error!(error = %e, "failed to sync routes");
    }
}
